'use strict';
const clone=x=>Array.isArray(x)?x.map(clone):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,clone(v)])):x;
const asset=n=>STARTER_ASSETS[n]||'';
function defaultProject(){
 const names=['Тесто','Томатный соус','Сыр','Пепперони','Грибы','Помидоры','Базилик','Оливки','Ветчина','Курица','Сладкий перец','Кукуруза','Ананас','Лук'],keys=['dough','sauce','cheese','pepperoni','mushrooms','tomato','basil','olives','ham','chicken','pepper','corn','pineapple','onion'];
 const recipes=[{id:'combo',name:'Комбо',image:asset('pizza-combo'),steps:['dough','sauce','cheese','pepperoni','mushrooms','olives']},{id:'margherita',name:'Маргарита',image:asset('pizza-margherita'),steps:['dough','sauce','cheese','tomato','basil']},{id:'pepperoni',name:'Пепперони',image:asset('pizza-pepperoni'),steps:['dough','sauce','cheese','pepperoni']},{id:'mushroom',name:'Грибная',image:asset('pizza-mushroom'),steps:['dough','sauce','cheese','mushrooms']},{id:'combo12',name:'Большое комбо',image:asset('pizza-combo12'),steps:keys.slice(0,12)},{id:'combo14',name:'Суперкомбо',image:asset('pizza-combo14'),steps:[...keys]}];
 recipes.forEach(r=>{r.voiceAudio=asset('voice-'+r.id);r.voiceText='Приготовь мне, пожалуйста, пиццу «'+r.name+'»!'});
 return {schemaVersion:1,editorVersion:'1.2.1',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),title:'Пиццерия знаний',description:'Каждый ингредиент — новое открытие. Выполни задания и приготовь самую вкусную пиццу!',titleEnabled:true,language:'ru',volume:.5,
 screens:{title:asset('interior'),kitchen:asset('interior'),counter:asset('counter-deep'),base:asset('dough'),menu:asset('menu'),winImage:asset('pizza-combo'),loseImage:'',winTitle:'Отличная работа, шеф!',loseTitle:'Попробуем ещё раз?',winText:'Все заказы готовы. Спасибо за вкусный урок!',loseText:'Немного практики — и всё получится.'},recipes,
 orders:[{id:'order-1',name:'Алекс',recipeId:'combo',recipe:'Комбо',requestPrefix:'Приготовь мне, пожалуйста, пиццу',message:'Приготовь мне, пожалуйста, пиццу «Комбо»!',client:asset('customer-plain'),finished:asset('pizza-combo'),steps:[...recipes[0].steps]}],
 ingredients:keys.map((id,i)=>({id,name:names[i],image:asset(id)||asset('topping-'+id),toppingImage:id==='dough'?asset('dough'):asset('topping-'+id),isBase:id==='dough',taskId:'task-'+id,placement:id==='tomato'?{x:18,y:8,w:33,h:33,rotation:0,opacity:1,z:i+3}:{x:7,y:7,w:86,h:86,rotation:0,opacity:1,z:i+3},copies:id==='tomato'?[{x:53,y:12,w:33,h:33,rotation:0,opacity:1,z:i+3},{x:12,y:42,w:33,h:33,rotation:0,opacity:1,z:i+3},{x:52,y:45,w:33,h:33,rotation:0,opacity:1,z:i+3},{x:34,y:28,w:33,h:33,rotation:0,opacity:1,z:i+3}]:[]})),
 tasks:keys.map((id,i)=>({id:'task-'+id,type:(['single','multiple','oral','order','input','single','single','single'][i]||'single'),question:['Сколько будет 2 + 3?','Выберите чётные числа.','Назовите три овоща.','Расположите числа по возрастанию.','Сколько будет 3 × 3?','Какого цвета спелый помидор?','Базилик — это…','Сколько будет 4 + 4?','Сколько будет 6 + 4?','Какое число больше остальных?','Продолжите ряд: 2, 4, 6, …','Сколько десятков в числе 30?','Какое число нечётное?','Сколько будет 12 − 7?'][i],options:[['4','5','6'],['2','3','4'],[],['1','2','3'],[],['Красный','Синий','Белый'],['Пряная трава','Фрукт','Злак'],['6','7','8'],['8','10','12'],['4','9','6'],['7','8','9'],['2','3','4'],['2','5','8'],['4','5','6']][i],correct:i===1?[0,2]:i===0?[1]:i===7?[2]:i>=8?[1]:[0],accepted:['9','девять'],reference:'Например: морковь, огурец, помидор.',explanation:'Внимательно прочитайте условие и попробуйте ещё раз.',shuffle:true,normalize:true,caseSensitive:false,image:''})),
 style:{accent:'#2f7f78',card:'#fff8e9',font:'Arial, sans-serif',radius:16,questionSize:24,buttonBg:'#2f7f78',buttonText:'#ffffff',buttonSize:18,buttonHeight:44,buttonPadding:20,buttonGlow:false,glowColor:'#eab866',glowSize:18,answerBg:'#fff6df',answerText:'#35483e'},
 gameplay:{lives:3,timer:false,seconds:300,points:true,pointsPerTask:100,orderPoints:250,bonuses:true,combo:true,penalty:false,strict:true,explain:false},audio:{enabled:true,builtIn:true,voice:true,voiceVolume:1,speechRate:.85},inventory:{columns:2,cellHeight:74,squareCells:true},
 transform:{customer:{x:4,y:14,w:39,h:84,rotation:0,opacity:1,z:3},counter:{x:1,y:30,w:98,h:66,rotation:0,opacity:1,z:2},menu:{x:4,y:17,w:30,h:70,rotation:0,opacity:1,z:2},pizza:{x:38,y:31,w:48,h:48,rotation:0,opacity:1,z:6},tray:{x:3,y:24,w:27,h:66,rotation:0,opacity:1,z:8}}};
}
function migrateProject(q){
 const defaults=defaultProject();if(!q||q.schemaVersion!==1)throw Error('Неподдерживаемая версия проекта.');
 const previous=q.editorVersion||'1.0.0',upgrading=!['1.2.0','1.2.1'].includes(previous);
 q.style={...defaults.style,...q.style};q.audio={...defaults.audio,...q.audio};q.inventory={...defaults.inventory,...q.inventory};q.transform={...defaults.transform,...q.transform};
 if(previous==='1.0.0'){q.screens.counter=defaults.screens.counter;q.transform.customer=clone(defaults.transform.customer);q.transform.counter=clone(defaults.transform.counter);}
 if(upgrading){const ids=new Set(q.ingredients.map(i=>i.id));defaults.ingredients.forEach(i=>{if(!ids.has(i.id)){q.ingredients.push(clone(i));if(!q.tasks.some(t=>t.id===i.taskId))q.tasks.push(clone(defaults.tasks.find(t=>t.id===i.taskId)))}});}
 if(!q.recipes?.length)q.recipes=clone(defaults.recipes);
 else if(upgrading)defaults.recipes.filter(r=>['combo12','combo14'].includes(r.id)&&!q.recipes.some(existing=>existing.id===r.id)).forEach(r=>q.recipes.push(clone(r)));
 q.ingredients.forEach(i=>{if(!i.toppingImage)i.toppingImage=asset('topping-'+i.id)||i.image;if(!i.placement)i.placement={x:7,y:7,w:86,h:86,rotation:0,opacity:1,z:3};i.isBase=i.isBase??i.id==='dough'});
 if(upgrading)q.recipes.forEach(r=>{const preset=defaults.recipes.find(d=>d.id===r.id);if(!r.voiceAudio&&preset){r.voiceAudio=preset.voiceAudio;r.voiceText=preset.voiceText;}});
 q.orders.forEach(o=>{if(o.client===asset('customer'))o.client=asset('customer-plain');o.recipeId=o.recipeId||q.recipes.find(r=>r.name===o.recipe||r.steps.join()===o.steps.join())?.id||'custom';o.requestPrefix=o.requestPrefix||'Приготовь мне, пожалуйста, пиццу'});
 q.editorVersion='1.2.1';return q;
}
let project=defaultProject(),tab=0,testing=false,history=[],future=[],optimized=false,revision=0,exportRevision=-1,exportHtml='',autosaveTimer,db,selectedOrder=0,selectedIngredient='dough',selectedRecipe='combo',selectedObject='customer',previewTask='';
const tabs=['Проект','Титульный лист','Клиенты и заказы','Меню и пиццы','Кухня и раскладка','Ингредиенты','Задания','Кнопки и стиль','Жизни, таймер, баллы','Звуки','Финальные экраны'];
const types={single:'Один ответ',multiple:'Несколько ответов',oral:'Устный ответ',order:'Расставить по порядку',input:'Ввод ответа'};
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function checkpoint(){history.push(clone(project));if(history.length>30)history.shift();future=[]}
function invalidate(){revision++;exportHtml='';$('#code').value='';$('#size').textContent='Настройки изменены. Повторите экспорт для актуального кода.';project.updatedAt=new Date().toISOString();clearTimeout(autosaveTimer);autosaveTimer=setTimeout(persist,700)}
function change(fn,rebuild=false){checkpoint();fn();invalidate();preview();if(rebuild)panel()}
function field(parent,label,value,fn,type='text',limits={}){
 if(type==='checkbox'){const line=el('label',undefined,'checkline'),n=el('input');n.type=type;n.checked=value;n.onchange=()=>change(()=>fn(n.checked));line.append(n,el('span',label));parent.append(line);return n}
 const l=el('label',label),n=el(type==='textarea'?'textarea':'input');if(type!=='textarea')n.type=type;n.value=value??'';Object.assign(n,limits);n.addEventListener(['text','textarea','number','color','range'].includes(type)?'input':'change',()=>{if((type==='number'||type==='range')&&n.value==='')return;change(()=>fn(type==='number'||type==='range'?Number(n.value):n.value))});parent.append(l,n);return n;
}
function select(parent,label,value,options,fn,mutates=true){parent.append(el('label',label));const n=el('select');Object.entries(options).forEach(([v,t])=>{const option=el('option',t);option.value=v;n.append(option)});n.value=value;n.onchange=()=>mutates?change(()=>fn(n.value),true):fn(n.value);parent.append(n);return n}
function btn(parent,label,fn,cls=''){const b=el('button',label,cls);b.onclick=fn;parent.append(b);return b}
function group(parent,title,open=false){const details=el('details',undefined,'control-group');details.open=open;details.append(el('summary',title));const body=el('div',undefined,'group-body');details.append(body);parent.append(details);return body}
function selectedClient(){selectedOrder=Math.min(selectedOrder,project.orders.length-1);return project.orders[selectedOrder]}
function recipeOptions(){return Object.fromEntries(project.recipes.map(r=>[r.id,r.name]))}
function ingredientOptions(){return Object.fromEntries(project.ingredients.map(i=>[i.id,i.name]))}
function setRecipe(o,id){const r=project.recipes.find(r=>r.id===id);if(!r)return;o.recipeId=id;o.recipe=r.name;o.steps=[...r.steps];o.finished=r.image;o.message=(o.requestPrefix||'Приготовь мне, пожалуйста, пиццу')+' «'+r.name+'»!'}
function chooseIngredient(s){if(!project.ingredients.some(i=>i.id===selectedIngredient))selectedIngredient=project.ingredients[0]?.id;select(s,'Ингредиент',selectedIngredient,ingredientOptions(),v=>{selectedIngredient=v;previewTask='';panel();preview()},false);return project.ingredients.find(i=>i.id===selectedIngredient)}
async function readMedia(file,light=false){if(!file||file.size>20*1024*1024)throw Error('Максимальный размер файла — 20 МБ.');if(!/^image\/(png|jpeg|webp|gif)$|^audio\//.test(file.type))throw Error('Выберите PNG, JPG, WebP, GIF или аудиофайл.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});if(file.type==='image/gif'||file.type.startsWith('audio/'))return src;return compressImage(src,light?1100:1920,light?.76:.86)}
async function compressImage(src,max,quality){const im=new Image();im.src=src;await im.decode();const c=document.createElement('canvas'),ratio=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const out=c.toDataURL('image/webp',quality);return out.length<src.length?out:src}
function upload(parent,label,get,set,audio=false){parent.append(el('label',label));const row=el('div',undefined,'upload-row'),n=el('input');n.type='file';n.accept=audio?'audio/*':'image/png,image/jpeg,image/webp,image/gif';n.onchange=async()=>{try{const f=n.files[0],src=await readMedia(f);change(()=>set(src));toast(`Загружено: ${(f.size/1024).toFixed(0)} КБ → ${(src.length*.75/1024).toFixed(0)} КБ`)}catch(e){toast(e.message)}};row.append(n);if(get())btn(row,'↺',()=>change(()=>set(''),true),'reset-upload');parent.append(row)}
function panel(){
 const s=$('#settings'),scroll=s.scrollTop;s.replaceChildren();$('#tabs').replaceChildren();const nav=el('select');nav.setAttribute('aria-label','Раздел редактора');tabs.forEach((name,i)=>{const o=el('option',(i+1)+'. '+name);o.value=i;nav.append(o)});nav.value=tab;nav.onchange=()=>{tab=Number(nav.value);testing=false;panel();$('#settings').scrollTop=0;preview()};$('#tabs').append(nav);s.append(el('h2',tabs[tab]));
 if(tab===0){field(s,'Название игры',project.title,v=>project.title=v);field(s,'Описание',project.description,v=>project.description=v,'textarea');select(s,'Язык кнопок',project.language,{ru:'Русский',en:'English',ar:'العربية (English)',he:'עברית (English)',fa:'فارسی (English)'},v=>project.language=v);field(s,'Громкость эффектов и музыки',project.volume,v=>project.volume=v,'range',{min:0,max:1,step:.05});s.append(el('p','Автосохранение включено. Скачивайте JSON для переноса проекта.','hint'));btn(s,'Новый проект',()=>{if(confirm('Сбросить текущий проект?'))change(()=>{project=defaultProject();selectedOrder=0;selectedIngredient='dough'},true)})}
 if(tab===1){field(s,'Показывать титульный экран',project.titleEnabled,v=>project.titleEnabled=v,'checkbox');field(s,'Название',project.title,v=>project.title=v);field(s,'Описание',project.description,v=>project.description=v,'textarea');const g=group(s,'Фон и меню');upload(g,'Фон титульного экрана',()=>project.screens.title,v=>project.screens.title=v||asset('interior'));upload(g,'Изображение меню',()=>project.screens.menu,v=>project.screens.menu=v||asset('menu'));}
 if(tab===2){select(s,'Заказ',String(selectedOrder),Object.fromEntries(project.orders.map((o,i)=>[i,(i+1)+'. '+o.name])),v=>{selectedOrder=Number(v);panel();preview()},false);const o=selectedClient();field(s,'Имя клиента',o.name,v=>o.name=v);select(s,'Пицца',o.recipeId,{custom:'Свой рецепт',...recipeOptions()},id=>setRecipe(o,id));field(s,'Начало реплики',o.requestPrefix,v=>{o.requestPrefix=v;o.message=v+' «'+o.recipe+'»!'});field(s,'Реплика клиента',o.message,v=>o.message=v,'textarea');const actions=el('div',undefined,'row');btn(actions,'+ Заказ',()=>change(()=>{const n=clone(o);n.id='order-'+Date.now();project.orders.push(n);selectedOrder=project.orders.length-1},true));if(project.orders.length>1)btn(actions,'Удалить',()=>{if(confirm('Удалить заказ?'))change(()=>{project.orders.splice(selectedOrder,1);selectedOrder=0},true)});s.append(actions);const media=group(s,'Изображения клиента и пиццы');upload(media,'Клиент / GIF',()=>o.client,v=>o.client=v||asset('customer-plain'));upload(media,'Готовая пицца',()=>o.finished,v=>o.finished=v||asset('pizza-combo'));const ingredients=group(s,'Состав заказа');project.ingredients.forEach(i=>field(ingredients,i.name,o.steps.includes(i.id),v=>{o.recipeId='custom';o.steps=v?[...o.steps,i.id]:o.steps.filter(id=>id!==i.id)},'checkbox'));transforms(group(s,'Положение и размер клиента'),'customer');}
 if(tab===3){select(s,'Редактируемая пицца',selectedRecipe,recipeOptions(),id=>{selectedRecipe=id;panel();preview()},false);const r=project.recipes.find(r=>r.id===selectedRecipe)||project.recipes[0];selectedRecipe=r.id;field(s,'Название',r.name,v=>{r.name=v;project.orders.filter(o=>o.recipeId===r.id).forEach(o=>setRecipe(o,r.id))});btn(s,'Выбрать для текущего клиента',()=>change(()=>setRecipe(selectedClient(),r.id),true),'primary');s.append(el('p','В игре меню кликабельное: выбранную пиццу заказывает клиент.','hint'));const media=group(s,'Изображение готовой пиццы');upload(media,'Пицца',()=>r.image,v=>{r.image=v||asset('pizza-combo');project.orders.filter(o=>o.recipeId===r.id).forEach(o=>setRecipe(o,r.id))});s.append(el('p',r.steps.length+' ингредиентов = '+r.steps.length+' заданий','hint'));const portions=group(s,'Дополнительные задания');select(portions,'Продукт для новой порции',selectedIngredient,Object.fromEntries(project.ingredients.filter(i=>!i.isBase).map(i=>[i.id,i.name])),v=>{selectedIngredient=v},false);btn(portions,'+ Порция с отдельным заданием',()=>addRecipePortion(r));const narration=group(s,'Озвучивание рецепта');upload(narration,'Своя запись заказа',()=>r.voiceAudio,v=>{r.voiceAudio=v;r.voiceText=(selectedClient().requestPrefix||'Приготовь мне, пожалуйста, пиццу')+' «'+r.name+'»!'},true);field(narration,'Текст записи',r.voiceText||'',v=>r.voiceText=v,'textarea');const compose=group(s,'Ингредиенты рецепта');project.ingredients.forEach(i=>field(compose,i.name,r.steps.includes(i.id),v=>{r.steps=v?[...r.steps,i.id]:r.steps.filter(id=>id!==i.id);project.orders.filter(o=>o.recipeId===r.id).forEach(o=>setRecipe(o,r.id))},'checkbox'));const acts=el('div',undefined,'row');btn(acts,'+ Пицца',()=>change(()=>{const n=clone(r);n.id='recipe-'+Date.now();n.name='Новая пицца';project.recipes.push(n);selectedRecipe=n.id},true));if(project.recipes.length>1)btn(acts,'Удалить',()=>{if(confirm('Удалить рецепт?'))change(()=>{project.recipes=project.recipes.filter(x=>x.id!==r.id);project.orders.filter(o=>o.recipeId===r.id).forEach(o=>setRecipe(o,project.recipes[0].id));selectedRecipe=project.recipes[0].id},true)});s.append(acts);}
 if(tab===4){select(s,'Заказ для раскладки',String(selectedOrder),Object.fromEntries(project.orders.map((o,i)=>[i,(i+1)+'. '+o.recipe])),v=>{selectedOrder=Number(v);panel();preview()},false);s.append(el('p','На тесте показаны все слои выбранного рецепта. Двигайте их и меняйте размер за зелёные маркеры. В игре они появятся после правильных ответов.','hint'));const o=selectedClient();select(s,'Объект',selectedObject,{counter:'Столешница',pizza:'Тесто / область сборки',tray:'Панель ингредиентов',...Object.fromEntries(o.steps.filter(id=>id!=='dough').flatMap(id=>{const i=project.ingredients.find(i=>i.id===id);return [['topping:'+id,i?.name||id],...(i?.copies||[]).map((_,n)=>['topping:'+id+':'+n,(i?.name||id)+' · копия '+(n+1)])]}))},v=>{selectedObject=v;panel();preview()},false);transforms(group(s,'Координаты и размер',true),selectedObject);const inventory=group(s,'Панель ингредиентов');field(inventory,'Число колонок',project.inventory.columns,v=>project.inventory.columns=Math.max(1,Math.min(5,Math.round(v))),'number',{min:1,max:5});field(inventory,'Квадратные ячейки',project.inventory.squareCells!==false,v=>project.inventory.squareCells=v,'checkbox');btn(inventory,'Сделать панель квадратной',()=>change(()=>{const tr=project.transform.tray;tr.w=Math.min(tr.w,78.75);tr.h=tr.w*16/9;selectedObject='tray'},true));s.append(el('p','Панель: ширина и высота меняются независимо за угловые маркеры. Квадратные ячейки подстраиваются под число колонок. Высота ниже используется, если квадратные ячейки выключены.','hint'));field(inventory,'Высота ячейки, px',project.inventory.cellHeight,v=>project.inventory.cellHeight=Math.max(60,Math.min(160,v)),'number',{min:60,max:160});const backgrounds=group(s,'Фон и пустой стол');for(const[k,title]of Object.entries({kitchen:'Фон кухни',counter:'Пустая столешница',base:'Тесто'}))upload(backgrounds,title,()=>project.screens[k],v=>project.screens[k]=v||asset(k==='kitchen'?'interior':k==='counter'?'counter-deep':'dough'));}
 if(tab===5){const i=chooseIngredient(s);if(i){field(s,'Название',i.name,v=>i.name=v);s.append(el('p','Панель выбора и слой на тесте используют разные изображения.','hint'));const media=group(s,'Картинки ингредиента',true);upload(media,'В панели (можно чашку)',()=>i.image,v=>i.image=v||asset(i.id)||asset('cheese'));upload(media,'На тесте (без посуды)',()=>i.toppingImage,v=>i.toppingImage=v||asset('topping-'+i.id));if(!i.isBase){transforms(group(s,'Раскладка на тесте'),'topping:'+i.id);btn(s,'+ Копия продукта на тесто',()=>change(()=>{i.copies=i.copies||[];i.copies.push({...clone(i.placement),x:Math.min(70,i.placement.x+5),y:Math.min(70,i.placement.y+5)});selectedObject='topping:'+i.id+':'+(i.copies.length-1)},true));if(i.copies?.length)btn(s,'Удалить последнюю копию',()=>change(()=>i.copies.pop(),true));}const actions=el('div',undefined,'row');btn(actions,'+ Ингредиент',addIngredient);btn(actions,'Удалить',()=>{if(confirm('Удалить ингредиент, задание и убрать его из рецептов?'))change(()=>{project.ingredients=project.ingredients.filter(j=>j.id!==i.id);project.tasks=project.tasks.filter(t=>t.id!==i.taskId);project.orders.forEach(o=>o.steps=o.steps.filter(id=>id!==i.id));project.recipes.forEach(r=>r.steps=r.steps.filter(id=>id!==i.id));selectedIngredient=project.ingredients[0]?.id},true)});s.append(actions)}}
 if(tab===6){const i=chooseIngredient(s),task=i&&project.tasks.find(t=>t.id===i.taskId);if(task){select(s,'Тип задания',task.type,types,v=>{task.type=v;previewTask=i.id});field(s,'Вопрос',task.question,v=>task.question=v,'textarea');if(['single','multiple','order'].includes(task.type)){field(s,task.type==='order'?'Карточки в правильном порядке':'Варианты — каждый с новой строки',task.options.join('\n'),v=>task.options=v.split('\n'),'textarea');if(task.type!=='order')field(s,'Правильные номера через запятую',task.correct.map(i=>i+1).join(', '),v=>task.correct=v.split(',').map(n=>Number(n.trim())-1));field(s,'Перемешивать',task.shuffle,v=>task.shuffle=v,'checkbox')}
  if(task.type==='input'){field(s,'Допустимые ответы — с новой строки',task.accepted.join('\n'),v=>task.accepted=v.split('\n'),'textarea');field(s,'Учитывать регистр',task.caseSensitive,v=>task.caseSensitive=v,'checkbox');field(s,'Нормализовать пробелы и ё/е',task.normalize,v=>task.normalize=v,'checkbox')}
  if(task.type==='oral')field(s,'Эталон самопроверки',task.reference,v=>task.reference=v,'textarea');const more=group(s,'Объяснение и картинка');field(more,'Объяснение ошибки',task.explanation,v=>task.explanation=v,'textarea');upload(more,'Изображение вопроса',()=>task.image,v=>task.image=v);
 }else if(i)btn(s,'Создать задание',()=>change(()=>{const q=clone(defaultProject().tasks[0]);q.id='task-'+i.id;i.taskId=q.id;project.tasks.push(q)},true));}
 if(tab===7){const buttons=group(s,'Все кнопки',true);field(buttons,'Цвет кнопок',project.style.buttonBg,v=>{project.style.buttonBg=v;project.style.accent=v},'color');field(buttons,'Цвет букв',project.style.buttonText,v=>project.style.buttonText=v,'color');const row=el('div',undefined,'row');field(row,'Шрифт, px',project.style.buttonSize,v=>project.style.buttonSize=v,'number',{min:10,max:40});field(row,'Высота, px',project.style.buttonHeight,v=>project.style.buttonHeight=v,'number',{min:32,max:90});buttons.append(row);field(buttons,'Ширина: отступы по бокам',project.style.buttonPadding,v=>project.style.buttonPadding=v,'range',{min:4,max:60,step:1});field(buttons,'Свечение кнопок',project.style.buttonGlow,v=>project.style.buttonGlow=v,'checkbox');field(buttons,'Цвет свечения',project.style.glowColor,v=>project.style.glowColor=v,'color');field(buttons,'Сила свечения',project.style.glowSize,v=>project.style.glowSize=v,'range',{min:0,max:50,step:1});const answers=group(s,'Кнопки вариантов ответа');field(answers,'Фон вариантов',project.style.answerBg,v=>project.style.answerBg=v,'color');field(answers,'Цвет букв вариантов',project.style.answerText,v=>project.style.answerText=v,'color');const card=group(s,'Карточка и шрифт');field(card,'Фон карточки',project.style.card,v=>project.style.card=v,'color');field(card,'Скругление',project.style.radius,v=>project.style.radius=v,'range',{min:0,max:40});field(card,'Размер вопроса',project.style.questionSize,v=>project.style.questionSize=v,'number',{min:14,max:72});select(card,'Шрифт',project.style.font,{'Arial, sans-serif':'Arial','Verdana, sans-serif':'Verdana','Georgia, serif':'Georgia','Tahoma, sans-serif':'Tahoma','Trebuchet MS, sans-serif':'Trebuchet MS','Times New Roman, serif':'Times New Roman','Courier New, monospace':'Courier New','Comic Sans MS, cursive':'Comic Sans MS','system-ui, sans-serif':'Системный'},v=>project.style.font=v)}
 if(tab===8){field(s,'Жизни',project.gameplay.lives,v=>project.gameplay.lives=Math.max(1,Math.min(10,v)),'number',{min:1,max:10});for(const[k,label]of Object.entries({timer:'Общий таймер игры',points:'Баллы',bonuses:'Бонусы',combo:'Множитель за серию',penalty:'Штраф за неверный ингредиент',strict:'Строго по рецепту',explain:'Объяснение после ошибки'}))field(s,label,project.gameplay[k],v=>project.gameplay[k]=v,'checkbox');const values=group(s,'Время и начисления');for(const[k,label]of Object.entries({seconds:'Время, секунды',pointsPerTask:'Баллы за задание',orderPoints:'Баллы за заказ'}))field(values,label,project.gameplay[k],v=>project.gameplay[k]=Math.max(1,v),'number',{min:1})}
 if(tab===9){field(s,'Звук включён',project.audio.enabled,v=>project.audio.enabled=v,'checkbox');field(s,'Встроенные звуковые эффекты',project.audio.builtIn,v=>project.audio.builtIn=v,'checkbox');field(s,'Клиент озвучивает заказ',project.audio.voice,v=>project.audio.voice=v,'checkbox');field(s,'Громкость эффектов и музыки',project.volume,v=>project.volume=v,'range',{min:0,max:1,step:.05});field(s,'Громкость речи',project.audio.voiceVolume,v=>project.audio.voiceVolume=v,'range',{min:0,max:1,step:.05});field(s,'Темп для новых текстов',project.audio.speechRate,v=>project.audio.speechRate=v,'range',{min:.65,max:1.1,step:.05});s.append(el('p','Готовые заказы используют отдельные русские аудиозаписи. Во время речи музыка и эффекты молчат. Для своих текстов можно загрузить запись во вкладке меню.','hint'));s.append(el('p','Щелчок, перенос, верный ответ, ошибка, готовность, выдача и финал работают без загрузки файлов.','hint'));btn(s,'▶ Прослушать встроенный эффект',playSample);for(const[k,label]of Object.entries({music:'Фоновая музыка',click:'Нажатие',order:'Заказ',pickup:'Захват ингредиента',drop:'Перенос на тесто',correct:'Правильный ответ',wrong:'Ошибка',ready:'Готовая пицца',serve:'Выдача',win:'Победа',lose:'Поражение'})){const g=group(s,label);upload(g,'Заменить своим звуком',()=>project.audio[k],v=>project.audio[k]=v,true);if(project.audio[k])btn(g,'▶ Прослушать',()=>{const a=new Audio(project.audio[k]);a.volume=project.volume;a.play().catch(()=>toast('Не удалось воспроизвести'))})}}
 if(tab===10){for(const[key,title]of [['win','Победа'],['lose','Поражение']]){const g=group(s,title,key==='win');field(g,'Заголовок',project.screens[key+'Title'],v=>project.screens[key+'Title']=v);field(g,'Текст',project.screens[key+'Text'],v=>project.screens[key+'Text']=v,'textarea');upload(g,'Картинка / GIF',()=>project.screens[key+'Image'],v=>project.screens[key+'Image']=v);btn(g,'Показать '+title.toLowerCase(),()=>preview(key==='win'?'WIN':'LOSE'))}}
 s.scrollTop=scroll;fitSidebar();
}
function addIngredient(){change(()=>{const id='ingredient-'+Date.now(),q={...clone(defaultProject().tasks[0]),id:'task-'+id,question:'Новый вопрос',type:'single',options:['Верный ответ','Другой ответ'],correct:[0]};project.ingredients.push({id,name:'Новый ингредиент',image:asset('cheese'),toppingImage:asset('topping-cheese'),taskId:q.id,placement:{x:10,y:10,w:80,h:80,rotation:0,opacity:1,z:5}});project.tasks.push(q);selectedIngredient=id},true)}
function addRecipePortion(recipe){const source=project.ingredients.find(i=>i.id===selectedIngredient&&!i.isBase)||project.ingredients.find(i=>!i.isBase);if(!source){toast('Сначала добавьте продукт.');return}change(()=>{const n=clone(source),id='portion-'+Date.now();n.id=id;n.name=source.name+' · новая порция';n.taskId='task-'+id;n.isBase=false;n.copies=[];n.placement={...clone(source.placement),x:20,y:20,w:45,h:45};const task=clone(project.tasks.find(t=>t.id===source.taskId)||defaultProject().tasks[0]);task.id=n.taskId;task.question='Новое задание: '+source.name;project.ingredients.push(n);project.tasks.push(task);recipe.steps.push(id);project.orders.filter(o=>o.recipeId===recipe.id).forEach(o=>setRecipe(o,recipe.id));selectedIngredient=id;},true);toast('Порция добавлена. Настройте её вопрос во вкладке «Задания».')}
function objectGeometry(key){if(key.startsWith('topping:')){const [,id,index]=key.split(':');const i=project.ingredients.find(i=>i.id===id);return index===undefined?i?.placement:i?.copies?.[Number(index)]}return project.transform[key]}
function transforms(parent,key){const tr=objectGeometry(key);if(!tr){parent.append(el('p','Выберите объект для настройки.','hint'));return}const grid=el('div',undefined,'coordinate-grid');for(const[k,label]of Object.entries({x:'X, %',y:'Y, %',w:'Ширина, %',h:'Высота, %',rotation:'Поворот',opacity:'Прозрачность',z:'Слой'})){const cell=el('div');field(cell,label,tr[k],v=>{tr[k]=k==='opacity'?Math.max(0,Math.min(1,v)):k==='w'||k==='h'?Math.max(3,Math.min(140,v)):v},'number',{step:k==='opacity'?.1:1});grid.append(cell)}parent.append(grid);btn(parent,'По центру',()=>change(()=>{tr.x=(100-tr.w)/2;tr.y=(100-tr.h)/2},true))}
function fitSidebar(){if(window.innerWidth<700){$('aside').style.height='';return}requestAnimationFrame(()=>{const frame=$('.frame').getBoundingClientRect(),main=$('main').getBoundingClientRect();$('aside').style.height=Math.max(300,frame.bottom-main.top)+'px'})}
function playSample(){try{const ctx=new(window.AudioContext||window.webkitAudioContext)();ctx.resume?.();[523,659,784].forEach((f,i)=>{const osc=ctx.createOscillator(),g=ctx.createGain(),at=ctx.currentTime+i*.12;osc.frequency.value=f;g.gain.setValueAtTime(project.volume*.12,at);g.gain.exponentialRampToValueAtTime(.001,at+.2);osc.connect(g);g.connect(ctx.destination);osc.start(at);osc.stop(at+.2)});setTimeout(()=>ctx.close(),1000)}catch(e){toast('Звуки недоступны в этом браузере')}}

function validate(p){const errors=[];if(!p||p.schemaVersion!==1)return ['Неподдерживаемая версия проекта.'];if(!Array.isArray(p.ingredients)||!Array.isArray(p.tasks)||!Array.isArray(p.orders)||!p.orders.length)return ['Проект должен содержать ингредиенты, задания и заказы.'];const ids=p.ingredients.map(i=>i.id);if(new Set(ids).size!==ids.length)errors.push('Повторяются идентификаторы ингредиентов.');[...p.orders,...(p.recipes||[]).map(r=>({...r,recipe:r.name}))].forEach((o,n)=>{if(!Array.isArray(o.steps)||!o.steps.length){errors.push(`Заказ ${n+1}: нет ингредиентов`);return}if(o.steps.filter(id=>p.ingredients.find(i=>i.id===id)?.isBase).length!==1)errors.push(`${o.recipe||o.name||'Рецепт'}: нужна ровно одна основа — тесто`);const seen=new Set();o.steps.forEach(id=>{const i=p.ingredients.find(i=>i.id===id),t=p.tasks.find(t=>t.id===i?.taskId);if(!i||!t){errors.push(`Заказ ${n+1}: отсутствует ингредиент или задание (${id})`);return}if(seen.has(t.id))errors.push(`Заказ ${n+1}: повторяется задание`);seen.add(t.id);if(!t.question?.trim()||!types[t.type])errors.push(`${i.name}: заполните вопрос и тип`);if(['single','multiple','order'].includes(t.type)){if(!Array.isArray(t.options)||t.options.length<2||t.options.length>10||t.options.some(v=>typeof v!=='string'||!v.trim()))errors.push(`${i.name}: нужно 2–10 непустых вариантов`);if(t.type!=='order'&&(!Array.isArray(t.correct)||!t.correct.length||t.correct.some(v=>!Number.isInteger(v)||v<0||v>=t.options.length)||new Set(t.correct).size!==t.correct.length||(t.type==='single'&&t.correct.length!==1)))errors.push(`${i.name}: неверные номера правильных ответов`)}if(t.type==='input'&&(!Array.isArray(t.accepted)||!t.accepted.some(v=>v.trim())))errors.push(`${i.name}: нет допустимого ответа`);});});return errors}
function canRun(){const e=validate(project);$('#issues').textContent=e.join('\n');if(e.length)toast('Исправьте ошибки во вкладке «Задания»');return !e.length}
function safeJson(x){return JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')}
function html(p,mode,editing=false,compact=false){let css=compact?PIZZA_CSS.replace(/\s+/g,' ').trim():PIZZA_CSS;let runtime=pizzeriaRuntime.toString();if(!editing){runtime=runtime.replace(/ function transform\(box,key,tr\)\{[\s\S]*?(?= function startAudio)/,'').replace('if(editing)transform(box,key,tr);','').replace('if(editing&&layoutVisible)transform(topping,key,tr);','').replace("if(editing)transform(tray,'tray',trayGeometry);",'');css=css.replace(/\.editable[^}]*}/g,'');}let data=clone(p),media={},counter=0,preamble='';if(compact){const refs=new Map();function pack(o){for(const[k,v]of Object.entries(o)){if(typeof v==='string'&&v.startsWith('data:')){if(!refs.has(v)){const id='@pizza-media-'+counter++;refs.set(v,id);media[id]=v}o[k]=refs.get(v)}else if(v&&typeof v==='object')pack(v)}}pack(data);preamble='const media='+safeJson(media)+';function unpack(o){for(const k of Object.keys(o)){const v=o[k];if(typeof v==="string"&&Object.prototype.hasOwnProperty.call(media,v))o[k]=media[v];else if(v&&typeof v==="object")unpack(v)}return o}';}const payload=compact?'unpack('+safeJson(data)+')':safeJson(data);return '<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Пиццерия</title><style>'+css+'</style><body><div id="root"></div><script>'+preamble+'('+runtime+')('+payload+','+JSON.stringify(mode)+','+editing+');<\/script></body></html>'}
function preview(mode){
 const normal=['TITLE','TITLE','CUSTOMER','MENU','PREP','PREP','TASK','TASK','PREP','PREP','WIN'][tab];
 const copy=clone(project);if(!testing){copy.orders=[clone(selectedClient())];if(tab===5||tab===6){if(!copy.orders[0].steps.includes(selectedIngredient))copy.orders[0].steps.push(selectedIngredient)}if(tab===6){const i=copy.ingredients.find(i=>i.id===selectedIngredient);copy.previewTaskId=i?.taskId;copy.previewIngredientId=i?.id;}}
 $('#screenLabel').textContent=testing?'Тест игры':tabs[tab];$('#game').srcdoc=html(copy,mode||(testing?(copy.titleEnabled?'TITLE':copy.recipes?.length?'MENU':'CUSTOMER'):normal),!testing,true);$('#test').textContent=testing?'↻ Начать заново':'▶ Тестировать';fitSidebar();
}
function runtimeProject(p){const q=clone(p),used=new Set([...q.orders.flatMap(o=>o.steps),...(q.recipes||[]).flatMap(r=>r.steps)]);if(!q.titleEnabled)q.screens.menu='';q.ingredients=q.ingredients.filter(i=>used.has(i.id));const taskIds=new Set(q.ingredients.map(i=>i.taskId));q.tasks=q.tasks.filter(t=>taskIds.has(t.id));if(!q.gameplay.explain)q.tasks.forEach(t=>delete t.explanation);delete q.createdAt;delete q.updatedAt;delete q.editorVersion;delete q.schemaVersion;delete q.previewTaskId;delete q.previewIngredientId;return q}
async function exportGame(light=optimized){if(!canRun())throw Error('Экспорт остановлен: исправьте задания.');const snapshot=clone(project),snapshotRevision=revision;const before=html(runtimeProject(snapshot),snapshot.titleEnabled?'TITLE':snapshot.recipes?.length?'MENU':'CUSTOMER'),q=runtimeProject(snapshot);if(light){const cache=new Map();async function walk(o){for(const[k,v]of Object.entries(o)){if(typeof v==='string'&&/^data:image\/(png|jpeg|webp);/.test(v)){if(!cache.has(v))cache.set(v,await compressImage(v,1100,.76));o[k]=cache.get(v)}else if(v&&typeof v==='object')await walk(v)}}await walk(q)}let out=html(q,q.titleEnabled?'TITLE':q.recipes?.length?'MENU':'CUSTOMER',false,light);if(out.length>before.length)out=before;exportHtml=out;exportRevision=snapshotRevision;const bytes=x=>new Blob([x]).size,a=bytes(before),b=bytes(out);$('#size').textContent=`${(a/1024).toFixed(0)} КБ → ${(b/1024).toFixed(0)} КБ · экономия ${Math.max(0,(1-b/a)*100).toFixed(1)}%${light?' · облегчённый экспорт':''}`;$('#code').value=embed(out);return out}
function embed(code){const attr=code.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return '<iframe title="Пиццерия" style="width:100%;aspect-ratio:16/9;border:0" sandbox="allow-scripts" srcdoc="'+attr+'" allow="autoplay; fullscreen" allowfullscreen></iframe>'}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#save').onclick=()=>download(JSON.stringify(project,null,2),'pizzeria-project.json','application/json');$('#load').onclick=()=>$('#import').click();$('#import').onchange=async()=>{try{const file=$('#import').files[0];if(file.size>50*1024*1024)throw Error('Проект слишком большой (лимит 50 МБ).');const q=migrateProject(JSON.parse(await file.text()));if(!q.screens||!q.style||!q.gameplay||!q.audio||!q.transform)throw Error('Файл не содержит настройки проекта.');const issues=validate(q);if(issues.length)throw Error(issues.join('\n'));validateMedia(q);change(()=>project=q,true);toast('Проект загружен')}catch(e){toast('Ошибка загрузки: '+e.message)}$('#import').value=''};
function validateMedia(q){function walk(o){for(const[k,v]of Object.entries(o)){if(typeof v==='string'&&['image','toppingImage','client','finished','title','kitchen','counter','base','menu','winImage','loseImage'].includes(k)&&v.startsWith('data:')&&!/^data:image\/(png|jpeg|webp|gif);base64,/.test(v))throw Error('Неподдерживаемое изображение');if(k==='voiceAudio'&&v&&!/^data:audio\/[\w.+-]+;base64,/.test(v))throw Error('Запись заказа должна быть встроена');if(v&&typeof v==='object')walk(v)}}walk(q);for(const [key,v] of Object.entries(q.audio))if(!['voiceURI'].includes(key)&&typeof v==='string'&&v&&!/^data:audio\/[\w.+-]+;base64,/.test(v))throw Error('Аудио должно быть встроено в проект')}
$('#download').onclick=async()=>{try{download(await exportGame(),'pizzeria-game.html','text/html')}catch(e){toast(e.message)}};$('#optimize').onclick=async()=>{const b=$('#optimize');b.disabled=true;b.textContent='Сжимаем…';try{optimized=true;await exportGame(true);toast('Код облегчён. GIF сохранены без изменений.')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='✦ Облегчить код'}};$('#copy').onclick=async()=>{try{if(!exportHtml||exportRevision!==revision)await exportGame();const code=embed(exportHtml);$('#code').value=code;try{await navigator.clipboard.writeText(code);toast('Код скопирован')}catch(e){$('#code').closest('details').open=true;$('#code').focus();$('#code').select();toast('Нажмите Ctrl+C / ⌘C, чтобы скопировать выделенный код.')}}catch(e){toast(e.message)}};
$('#test').onclick=()=>{if(canRun()){testing=true;preview()}};$('#preview').onclick=()=>{testing=false;preview()};
$('#undo').onclick=()=>{if(history.length){future.push(clone(project));project=history.pop();invalidate();panel();preview();persist()}};
$('#redo').onclick=()=>{if(future.length){history.push(clone(project));project=future.pop();invalidate();panel();preview();persist()}};
window.addEventListener('message',e=>{
 if(e.source!==$('#game').contentWindow||testing)return;
 if(e.data?.type==='pizza-recipe'){if(project.recipes.some(r=>r.id===e.data.recipeId)){change(()=>{setRecipe(selectedClient(),e.data.recipeId);tab=2},true)}return}
 if(e.data?.type!=='pizza-transform')return;
 const {key,value}=e.data;if(!value||['x','y','w','h','rotation','opacity','z'].some(k=>typeof value[k]!=='number'||!Number.isFinite(value[k])))return;
 const tr=objectGeometry(key);if(!tr)return;checkpoint();Object.assign(tr,value);selectedObject=key;invalidate();panel();persist();
});
window.addEventListener('resize',fitSidebar);
async function persist(){if(!db)return;try{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(project,'autosave');tx.onerror=()=>toast('Не удалось сохранить: скачайте JSON проекта.')}catch(e){toast('Автосохранение недоступно: скачайте JSON проекта.')}}
function initStorage(){if(!window.indexedDB){toast('Автосохранение недоступно. Скачивайте проект вручную.');return}const req=indexedDB.open('pizzeria-editor',1);req.onupgradeneeded=()=>req.result.createObjectStore('projects');req.onerror=()=>toast('Автосохранение недоступно. Скачивайте проект вручную.');req.onsuccess=()=>{db=req.result;const r=db.transaction('projects').objectStore('projects').get('autosave');r.onsuccess=()=>{if(r.result&&confirm('Найден сохранённый проект. Продолжить редактирование?')){try{project=migrateProject(r.result);panel();preview()}catch(e){toast('Не удалось восстановить проект: '+e.message)}}else persist()}}}
panel();preview();initStorage();
