const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tagName=tag;this.children=[];this.style={setProperty(){}};this.dataset={};this.classList={add(){},toggle(){}};this.textContent='';this.value='';}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}remove(){}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,right:1200,bottom:675,width:1200,height:675}}}
function harness(){const nodes={'#root':new Node('div')},document={querySelector:s=>nodes[s]||null,createElement:t=>new Node(t),body:new Node('body'),documentElement:new Node('html')},ctx={document,console,location:{origin:'https://example.com'},parent:{postMessage(){}},setTimeout:()=>1,clearInterval(){},setInterval:()=>1,Audio:class{play(){return Promise.resolve()}pause(){}},STARTER_ASSETS:new Proxy({},{get:()=> 'data:image/png;base64,AA=='})};vm.createContext(ctx);vm.runInContext(fs.readFileSync('game.js','utf8'),ctx);const source=fs.readFileSync('editor.js','utf8');vm.runInContext(source.slice(0,source.indexOf('let project=')),ctx);vm.runInContext("var p=defaultProject();var runtime=pizzeriaRuntime(p);",ctx);const all=n=>[n,...n.children.flatMap(all)];const click=text=>{const b=all(nodes['#root']).find(n=>n.tagName==='button'&&n.textContent===text&&!n.disabled);assert.ok(b,'Button exists: '+text);b.onclick()};return {ctx,nodes,all,click,state:()=>vm.runInContext('runtime.getState()',ctx),run:s=>vm.runInContext(s,ctx)}}
const g=harness();assert.equal(g.state().stage,'TITLE');g.click('Играть');assert.equal(g.state().stage,'CUSTOMER');g.click('Принять заказ');g.click('Тесто');g.click('4');assert.equal(g.state().lives,2);g.click('5');assert.deepEqual(Array.from(g.state().done),['dough']);g.click('Томатный соус');g.click('2');g.click('4');g.click('Проверить');g.click('Сыр');g.click('Показать ответ');g.click('Верно');g.click('Пепперони');
// For sorting, use runtime choices through actual arrow buttons until ordered.
for(let attempt=0;attempt<20;attempt++){const rows=g.all(g.nodes['#root']).filter(n=>n.className==='sortrow');const values=rows.map(r=>r.children[0].textContent);if(values.join()==='1,2,3')break;const index=values.findIndex((v,i)=>i>0&&Number(values[i-1])>Number(v));rows[index].children[1].onclick();}
g.click('Проверить');g.click('Грибы');const input=g.all(g.nodes['#root']).find(n=>n.tagName==='input');input.value=' 9 ';g.click('Проверить');assert.equal(g.state().stage,'READY');g.click('Отдать заказ');assert.equal(g.state().stage,'WIN');assert.equal(g.state().lives,2);assert.ok(g.state().score>0);g.click('Сыграть снова');assert.equal(g.state().lives,3);
const l=harness();l.click('Играть');l.click('Принять заказ');l.click('Тесто');for(let i=0;i<3;i++)l.click('4');assert.equal(l.state().stage,'LOSE');assert.equal(l.state().lives,0);
const multi=harness();multi.run("p.orders.push(JSON.parse(JSON.stringify(p.orders[0])));runtime=pizzeriaRuntime(p,'READY');");multi.click('Отдать заказ');assert.equal(multi.state().stage,'CUSTOMER');assert.equal(multi.state().order,1);
// Exercise export validation and script escaping without initializing the editor UI.
const src=fs.readFileSync('editor.js','utf8');g.run("var types={single:'single',multiple:'multiple',oral:'oral',order:'order',input:'input'};");g.run(src.slice(src.indexOf('function validate(p)'),src.indexOf('function canRun()')));assert.equal(g.run('validate(p).length'),0);g.run("p.orders[0].steps.push('missing')");assert.ok(g.run('validate(p).length')>0);g.run(src.slice(src.indexOf('function safeJson'),src.indexOf('function preview')));assert.ok(!g.run("safeJson({title:'</script><script>alert(1)</script>'})").includes('</script>'));
console.log('PASS: five task types; incorrect answers; victory; defeat; restart; multiple orders; validation; safe serialization.');
