const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{
 constructor(tag){this.tagName=tag;this.children=[];this.style={setProperty(k,v){this[k]=v}};this.dataset={};this.attrs={};this.listeners={};this._text='';this.value='';this.className='';this.scrollTop=0;this.classList={add:(...c)=>{this.className+=' '+c.join(' ')},remove:c=>{this.className=this.className.split(' ').filter(x=>x!==c).join(' ')},toggle:(c,on)=>{const has=this.className.split(' ').includes(c);if(on??!has)this.classList.add(c);else this.classList.remove(c)}};}
 get textContent(){return this._text+this.children.map(n=>n.textContent||'').join('')}set textContent(v){this._text=String(v);this.children=[]}
 append(...x){x.forEach(n=>{n.parentElement=this;this.children.push(n)})}replaceChildren(...x){this.children=[];this._text='';this.append(...x)}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(n=>n!==this)}
 setAttribute(k,v){this.attrs[k]=v}addEventListener(k,fn){(this.listeners[k]??=[]).push(fn)}removeEventListener(k,fn){this.listeners[k]=(this.listeners[k]||[]).filter(f=>f!==fn)}dispatch(k,e={}){(this.listeners[k]||[]).slice().forEach(fn=>fn({target:this,preventDefault(){},stopPropagation(){},...e}))}setPointerCapture(){}focus(){}click(){this.onclick?.()}
 getBoundingClientRect(){return {left:0,top:0,right:1200,bottom:675,width:1200,height:675}}querySelectorAll(s){return all(this).filter(n=>s.startsWith('.')?n.className.split(' ').includes(s.slice(1)):n.tagName===s)}querySelector(s){return this.querySelectorAll(s)[0]||null}
}
const all=n=>[n,...n.children.flatMap(all)];
function harness(editing=false,mode='TITLE',fullEditor=false){
 const nodes={'#root':new Node('div')};for(const id of ['settings','tabs','toast','code','size','screenLabel','game','test','save','load','import','download','optimize','copy','preview','undo','redo','issues'])nodes['#'+id]=new Node(id==='game'?'iframe':'div');for(const tag of ['aside','main','.frame'])nodes[tag]=new Node('div');nodes['#game'].contentWindow={};
 const speech=[],posts=[],stats={tones:0,audios:[],observers:[],events:{}},window={innerWidth:1200,addEventListener(name,fn){(stats.events[name]??=[]).push(fn)},removeEventListener(name,fn){stats.events[name]=(stats.events[name]||[]).filter(f=>f!==fn)},ResizeObserver:class{constructor(fn){this.fn=fn;this.targets=[];stats.observers.push(this)}observe(n){this.targets.push(n)}disconnect(){this.targets=[]}},speechSynthesis:{cancel(){},getVoices(){return [{lang:'ru-RU',voiceURI:'ru-test',name:'Russian',localService:true}]},speak(s){speech.push(s.text)}},SpeechSynthesisUtterance:class{constructor(text){this.text=text}},AudioContext:class{constructor(){this.currentTime=0;this.destination={}}resume(){return Promise.resolve()}close(){}createOscillator(){stats.tones++;return {frequency:{},connect(){},start(){},stop(){}}}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}}}};
 const document={querySelector:s=>nodes[s]||nodes['#root'].querySelector(s),createElement:t=>new Node(t),body:new Node('body'),documentElement:new Node('html')};
 const ctx={document,window,console,location:{origin:'https://example.com'},parent:{postMessage:d=>posts.push(JSON.parse(JSON.stringify(d)))},setTimeout:()=>1,clearTimeout(){},clearInterval(){},setInterval:()=>1,requestAnimationFrame:fn=>fn(),confirm:()=>true,Audio:class{constructor(src){this.src=src;this.paused=true;stats.audios.push(this)}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}},STARTER_ASSETS:new Proxy({},{get:(_,k)=>'data:image/png;base64,'+Buffer.from(String(k)).toString('base64')})};vm.createContext(ctx);
 vm.runInContext(fs.readFileSync('game.js','utf8'),ctx);const source=fs.readFileSync('editor.js','utf8');
 if(fullEditor)vm.runInContext(source,ctx);else{vm.runInContext(source.slice(0,source.indexOf('let project=')),ctx);vm.runInContext(`var p=defaultProject();var runtime=pizzeriaRuntime(p,${JSON.stringify(mode)},${editing});`,ctx)}
 const click=text=>{const b=all(nodes['#root']).find(n=>n.tagName==='button'&&!n.disabled&&(n.textContent===text||n.children.some(c=>c.tagName==='strong'&&c.textContent===text)));assert.ok(b,'Button exists: '+text);b.onclick()};
 return {ctx,nodes,all,click,window,posts,speech,stats,body:document.body,state:()=>vm.runInContext('runtime.getState()',ctx),run:s=>vm.runInContext(s,ctx)};
}
const g=harness();assert.equal(g.state().stage,'TITLE');g.click('Играть');assert.equal(g.state().stage,'MENU');g.click('Комбо');assert.equal(g.state().stage,'CUSTOMER');assert.equal(g.state().recipe,'Комбо');assert.ok(g.speech[0].includes('Комбо'));g.click('Принять заказ');assert.equal(g.nodes['#root'].querySelector('.pizza-zone').children.length,0,'Table starts empty');g.click('Рецепт · 1 / 1');assert.equal(g.nodes['#root'].querySelector('.recipe-ingredients').children.length,6);assert.ok(!g.nodes['#root'].querySelector('.recipe-grid'));g.click('Закрыть');g.click('Тесто');g.click('4');assert.equal(g.state().lives,2);assert.equal(g.nodes['#root'].querySelector('.pizza-zone').children.length,0,'Wrong answer does not place dough');g.click('5');assert.ok(g.nodes['#root'].querySelector('.pizza-zone').children.length>0);assert.deepEqual(Array.from(g.state().done),['dough']);g.click('Томатный соус');assert.equal(g.nodes['#root'].querySelector('.topping'),null,'Selected product has no pizza layer before answer');assert.equal(g.body.children.length,0);g.click('2');g.click('4');g.click('Проверить');
const sauce=g.nodes['#root'].querySelector('.topping');assert.equal(sauce.children[0].src,g.run("p.ingredients.find(i=>i.id==='sauce').toppingImage"));assert.notEqual(sauce.children[0].src,g.run("p.ingredients.find(i=>i.id==='sauce').image"));
g.click('Сыр');g.click('Показать ответ');g.click('Верно');g.click('Пепперони');for(let attempt=0;attempt<20;attempt++){const rows=g.all(g.nodes['#root']).filter(n=>n.className==='sortrow'),values=rows.map(r=>r.children[0].textContent);if(values.join()==='1,2,3')break;const index=values.findIndex((v,i)=>i>0&&Number(values[i-1])>Number(v));rows[index].children[1].onclick()}
g.click('Проверить');g.click('Грибы');const input=g.all(g.nodes['#root']).find(n=>n.tagName==='input');input.value=' 9 ';g.click('Проверить');g.click('Оливки');g.click('8');assert.equal(g.state().stage,'READY');g.click('Отдать заказ');assert.equal(g.state().stage,'WIN');assert.equal(g.state().lives,2);assert.ok(g.state().score>0);assert.ok(g.stats.tones>0);g.click('Сыграть снова');assert.equal(g.state().lives,3);
const l=harness();l.click('Играть');l.click('Комбо');l.click('Принять заказ');l.click('Тесто');for(let i=0;i<3;i++)l.click('4');assert.equal(l.state().stage,'LOSE');assert.equal(l.state().lives,0);
const menu=harness();menu.click('Играть');menu.click('Маргарита');assert.equal(menu.state().recipe,'Маргарита');assert.ok(menu.nodes['#root'].textContent.includes('Помидоры'));assert.ok(!menu.nodes['#root'].textContent.includes('Пепперони'));assert.ok(menu.speech[0].includes('Маргарита'));
const multi=harness();multi.run("p.orders.push(JSON.parse(JSON.stringify(p.orders[0])));runtime=pizzeriaRuntime(p,'READY');");multi.click('Отдать заказ');assert.equal(multi.state().stage,'CUSTOMER');assert.equal(multi.state().order,1);
const layout=harness(true,'PREP');const topping=layout.nodes['#root'].querySelector('.topping');assert.ok(topping,'All toppings visible for authoring');assert.ok(topping.querySelector('.se'),'Visible resize handle');topping.dispatch('pointerdown',{clientX:100,clientY:100,pointerId:1,button:0});topping.dispatch('pointermove',{clientX:160,clientY:140,pointerId:1});topping.dispatch('pointerup',{pointerId:1});assert.ok(layout.posts.at(-1).key.startsWith('topping:'));assert.notEqual(layout.posts.at(-1).value.x,7);
const client=harness(true,'CUSTOMER'),sprite=client.nodes['#root'].querySelector('.customer');sprite.dispatch('pointerdown',{clientX:100,clientY:100,pointerId:1,button:0});sprite.dispatch('pointermove',{clientX:100,clientY:280,pointerId:1});sprite.dispatch('pointerup',{pointerId:1});assert.ok(client.posts.at(-1).value.y>30,'Customer can move down past former bounds');const before=client.posts.at(-1).value.w;sprite.dispatch('pointerdown',{target:sprite.querySelector('.se'),clientX:100,clientY:100,pointerId:2,button:0});sprite.dispatch('pointermove',{clientX:160,clientY:140,pointerId:2});sprite.dispatch('pointerup',{pointerId:2});assert.ok(client.posts.at(-1).value.w>before,'Explicit handle resizes customer');
const source=fs.readFileSync('editor.js','utf8');g.run("var types={single:'single',multiple:'multiple',oral:'oral',order:'order',input:'input'}");g.run(source.slice(source.indexOf('function validate(p)'),source.indexOf('function canRun()')));assert.equal(g.run('validate(p).length'),0);g.run("p.recipes[0].steps.push('missing')");assert.ok(g.run('validate(p).length')>0);g.run(source.slice(source.indexOf('function safeJson'),source.indexOf('function preview')));assert.ok(!g.run("safeJson({title:'</script><script>alert(1)</script>'})").includes('</script>'));
const editor=harness(false,'TITLE',true);for(let i=0;i<11;i++)editor.run(`tab=${i};panel();preview()`);assert.equal(editor.nodes['#tabs'].children.length,1,'Compact section selector');editor.run('tab=6;panel()');assert.ok(editor.nodes['#settings'].querySelectorAll('textarea').length<=4,'Only one task editor is rendered');editor.run("project.style.buttonText='#ff0000';project.style.buttonGlow=true;preview()");assert.ok(editor.nodes['#game'].srcdoc.includes('#ff0000'));
const direct=harness();direct.click('Грибная');assert.equal(direct.state().recipe,'Грибная');assert.equal(direct.nodes['#root'].querySelector('.order-pizza').src,direct.run("p.recipes.find(r=>r.id==='mushroom').image"));
const pickup=harness(false,'PREP'),bowl=pickup.all(pickup.nodes['#root']).find(n=>n.tagName==='button'&&n.textContent==='Томатный соус');bowl.dispatch('pointerdown',{clientX:20,clientY:20,pointerId:1});assert.equal(pickup.body.querySelector('.dragghost'),null,'Press does not create a separate product');bowl.dispatch('pointermove',{clientX:80,clientY:80,pointerId:1});assert.equal(pickup.body.children.length,0,'Dragging does not create a separate product');assert.ok(pickup.nodes['#root'].querySelector('.drop-target'));bowl.dispatch('pointercancel',{pointerId:1});assert.equal(pickup.body.children.length,0);
const upgrade=harness();upgrade.run("var oldProject=defaultProject();oldProject.editorVersion='1.0.0';delete oldProject.recipes;oldProject.ingredients=oldProject.ingredients.slice(0,5);oldProject.tasks=oldProject.tasks.slice(0,5);oldProject.ingredients.forEach(i=>{delete i.toppingImage;delete i.placement});oldProject.tasks[0].question='Авторский вопрос';oldProject.orders[0].client=asset('customer');var upgraded=migrateProject(oldProject);");assert.equal(upgrade.run('upgraded.tasks[0].question'),'Авторский вопрос');assert.equal(upgrade.run('upgraded.ingredients.length'),14);assert.equal(upgrade.run('upgraded.orders[0].client'),upgrade.run("asset('customer-plain')"));
const style=harness();style.run("p.style.buttonText='#ff0000';p.style.buttonGlow=true;p.style.glowColor='#00ff00';runtime=pizzeriaRuntime(p);");assert.equal(style.ctx.document.documentElement.style['--buttonText'],'#ff0000');assert.ok(style.ctx.document.documentElement.style['--buttonGlow'].includes('#00ff00'));
console.log('PASS: five task types, lives, victory/defeat, clickable recipes, matching spoken order, topping-only rendering, pointer drag/resize, built-in sounds, all editor tabs, compact inspector, validation and escaping.');

const trayTest=harness(true,'PREP'),tray=trayTest.nodes['#root'].querySelector('.tray');tray.dispatch('pointerdown',{clientX:100,clientY:100,pointerId:1,button:0});tray.dispatch('pointermove',{clientX:240,clientY:200,pointerId:1});tray.dispatch('pointerup',{pointerId:1});assert.equal(trayTest.posts.at(-1).key,'tray');const trayWidth=trayTest.posts.at(-1).value.w;tray.dispatch('pointerdown',{target:tray.querySelector('.se'),clientX:100,clientY:100,pointerId:2,button:0});tray.dispatch('pointermove',{clientX:160,clientY:160,pointerId:2});tray.dispatch('pointerup',{pointerId:2});assert.ok(trayTest.posts.at(-1).value.w>trayWidth);trayTest.run("p.transform.tray={x:40,y:12,w:30,h:70,z:8};runtime=pizzeriaRuntime(p,'PREP');");assert.equal(trayTest.nodes['#root'].querySelector('.tray').style.left,'40%');
const empty=harness(false,'PREP');empty.click('Томатный соус');assert.equal(empty.state().stage,'PREP');assert.equal(empty.state().lives,3);assert.equal(empty.nodes['#root'].querySelector('.pizza-zone').children.length,0);
const large=harness();large.click('Играть');large.click('Большое комбо');assert.equal(large.run('p.recipes.find(r=>r.id==="combo12").steps.length'),12);large.click('Рецепт');assert.equal(large.nodes['#root'].querySelector('.recipe-ingredients').children.length,12);large.click('Закрыть');large.click('Выбрать другую пиццу');large.click('Суперкомбо');large.click('Рецепт');assert.equal(large.nodes['#root'].querySelector('.recipe-ingredients').children.length,14);
editor.run("selectedIngredient='ham';addRecipePortion(project.recipes.find(r=>r.id==='combo14'))");assert.equal(editor.run('project.recipes.find(r=>r.id==="combo14").steps.length'),15);assert.equal(editor.run('validate(project).length'),0);assert.equal(editor.run('new Set(project.ingredients.map(i=>i.taskId)).size'),15);
const voice=harness();voice.run("p.recipes[0].voiceAudio='data:audio/wav;base64,AAAA';p.audio.music='data:audio/wav;base64,BBBB';runtime=pizzeriaRuntime(p);");voice.click('Играть');const tonesBeforeVoice=voice.stats.tones;voice.click('Комбо');assert.equal(voice.state().voiceBusy,true);const voiceClip=voice.stats.audios.find(a=>a.src==='data:audio/wav;base64,AAAA');assert.ok(voiceClip);assert.equal(voiceClip.playbackRate,1);assert.equal(voice.stats.tones,tonesBeforeVoice,'No FX during speech');assert.ok(voice.stats.audios.filter(a=>a!==voiceClip).every(a=>a.paused),'Music paused during speech');voiceClip.onended();assert.equal(voice.state().voiceBusy,false);
console.log('PASS: empty initial table, recipe ingredient lists, 12/14-step combos, independent extra portions, movable/resizable tray, prerecorded narration without competing effects.');
const freeTray=harness(true,'PREP'),freeBox=freeTray.nodes['#root'].querySelector('.tray');freeBox.dispatch('pointerdown',{target:freeBox.querySelector('.se'),clientX:100,clientY:100,pointerId:3,button:0});freeBox.dispatch('pointermove',{clientX:100,clientY:200,pointerId:3});freeBox.dispatch('pointerup',{pointerId:3});assert.equal(freeTray.posts.at(-1).value.w,27,'Vertical resize preserves panel width');assert.ok(freeTray.posts.at(-1).value.h>66,'Vertical resize changes panel height');freeBox.dispatch('pointerdown',{target:freeBox.querySelector('.se'),clientX:100,clientY:100,pointerId:4,button:0});const oldTrayHeight=freeTray.posts.at(-1).value.h;freeBox.dispatch('pointermove',{clientX:180,clientY:100,pointerId:4});freeBox.dispatch('pointerup',{pointerId:4});assert.equal(freeTray.posts.at(-1).value.h,oldTrayHeight,'Horizontal resize preserves panel height');
for(let columns=1;columns<=5;columns++){const cells=harness(false,'PREP');cells.run(`p.inventory.columns=${columns};runtime=pizzeriaRuntime(p,'PREP')`);const grid=cells.nodes['#root'].querySelector('.tray-content');assert.equal(grid.style.gridTemplateColumns,`repeat(${columns},minmax(0,1fr))`);grid.clientWidth=312;cells.stats.observers.at(-1).fn();assert.equal(grid.style.gridAutoRows,((312-12-(columns-1)*6)/columns)+'px');const names=cells.nodes['#root'].querySelectorAll('.ingredient');assert.equal(names.length,14);assert.ok(names.every(n=>n.title===n.children[1].textContent&&n.attrs['aria-label']===n.title));}
const fixedCells=harness(false,'PREP');fixedCells.run("p.inventory.squareCells=false;p.inventory.cellHeight=96;runtime=pizzeriaRuntime(p,'PREP')");assert.equal(fixedCells.nodes['#root'].querySelector('.tray-content').style.gridAutoRows,'96px');
editor.run('tab=4;panel()');const squarePanel=editor.all(editor.nodes['#settings']).find(n=>n.tagName==='button'&&n.textContent==='Сделать панель квадратной');assert.ok(squarePanel);squarePanel.onclick();assert.equal(editor.run('project.transform.tray.h/project.transform.tray.w'),16/9,'Panel is a physical square on a 16:9 stage');assert.equal(editor.run('selectedObject'),'tray');editor.run("var authored12=defaultProject();authored12.editorVersion='1.2.0';authored12.inventory={columns:5,cellHeight:90};authored12.transform.tray={x:15,y:30,w:40,h:45};authored12.ingredients.pop();var migrated121=migrateProject(authored12)");assert.equal(editor.run('migrated121.ingredients.length'),13,'Patch upgrade preserves authored ingredients');assert.equal(editor.run('migrated121.inventory.squareCells'),true);assert.equal(editor.run('migrated121.transform.tray.h'),45);
console.log('PASS: independent tray width/height, square panel shortcut, adaptive square cells for 1–5 columns, fixed-height option and project migration.');

const fitting=harness(false,'PREP'),fitGrid=fitting.nodes['#root'].querySelector('.tray-content');fitGrid.clientWidth=260;const fitLabel=fitGrid.querySelector('.ingredient-label');fitLabel.textContent='Очень длинное название ингредиента без сокращений';Object.defineProperties(fitLabel,{scrollWidth:{get(){return Math.min(this.textContent.length*parseFloat(this.style.fontSize)*.6,this.clientWidth)}},scrollHeight:{get(){const size=parseFloat(this.style.fontSize),capacity=Math.max(1,Math.floor(this.clientWidth/(size*.6)));return Math.ceil(this.textContent.length/capacity)*size*1.1}}});
for(const [width,height] of [[18,6],[42,18],[96,34],[240,90]]){fitLabel.clientWidth=width;fitLabel.clientHeight=height;fitting.stats.observers.at(-1).fn();assert.ok(parseFloat(fitLabel.style.fontSize)>0,'Label has nonzero font size');assert.ok(fitLabel.scrollHeight<=height&&fitLabel.scrollWidth<=width,'Full wrapped label fits both dimensions');assert.equal(fitLabel.textContent,'Очень длинное название ингредиента без сокращений');}
const fontLarge=parseFloat(fitLabel.style.fontSize);fitLabel.clientWidth=24;fitLabel.clientHeight=8;fitting.stats.observers.at(-1).fn();assert.ok(parseFloat(fitLabel.style.fontSize)<fontLarge);fitLabel.clientWidth=240;fitLabel.clientHeight=90;fitting.stats.observers.at(-1).fn();assert.equal(parseFloat(fitLabel.style.fontSize),fontLarge,'Enlarging restores readable font size');fitLabel.clientWidth=0;fitLabel.clientHeight=0;fitting.stats.observers.at(-1).fn();assert.equal(parseFloat(fitLabel.style.fontSize),fontLarge,'Hidden preview does not erase text');fitting.run('runtime.destroy()');assert.equal(fitting.stats.observers.at(-1).targets.length,0);assert.equal(fitting.stats.events.resize.length,0);
console.log('PASS: measured label fitting for narrow/wide and short/tall cells, font recovery after resize, hidden previews, observer cleanup and no premature product copies.');

const exportedCSS=g.run("html(defaultProject(),'PREP',false,true)").match(/<style>([\s\S]*?)<\/style>/)[1];assert.ok(/(?:^|})\.ingredient\{/.test(exportedCSS),'Export keeps ingredient cell selector');assert.ok(/(?:^|})\.ingredient-label\{/.test(exportedCSS),'Export keeps visible label selector');assert.ok(!/\.tray\.ingredient/.test(exportedCSS),'Removing editor CSS does not concatenate selectors');assert.ok(!/\.editable/.test(exportedCSS),'Export removes complete editor-only rules');assert.ok(!/cqw|cqh|container-type:size/.test(exportedCSS));console.log('PASS: standalone CSS retains ingredient cells and labels after complete editor-rule removal.');
